
package introsde.assignment3.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://soap.assignment3.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonListResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonService/readPersonListRequest", output = "http://soap.assignment3.introsde/PersonService/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorldAsString", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetHelloWorldAsString")
    @ResponseWrapper(localName = "getHelloWorldAsStringResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetHelloWorldAsStringResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonService/getHelloWorldAsStringRequest", output = "http://soap.assignment3.introsde/PersonService/getHelloWorldAsStringResponse")
    public String getHelloWorldAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonService/readPersonRequest", output = "http://soap.assignment3.introsde/PersonService/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePersonResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonService/updatePersonRequest", output = "http://soap.assignment3.introsde/PersonService/updatePersonResponse")
    public Person updatePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.CreatePersonResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonService/createPersonRequest", output = "http://soap.assignment3.introsde/PersonService/createPersonResponse")
    public Person createPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.DeletePersonResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonService/deletePersonRequest", output = "http://soap.assignment3.introsde/PersonService/deletePersonResponse")
    public void deletePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Activity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferences")
    @ResponseWrapper(localName = "readPersonPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonService/readPersonPreferencesRequest", output = "http://soap.assignment3.introsde/PersonService/readPersonPreferencesResponse")
    public List<Activity> readPersonPreferences(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Activity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPreferences")
    @ResponseWrapper(localName = "readPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonService/readPreferencesRequest", output = "http://soap.assignment3.introsde/PersonService/readPreferencesResponse")
    public List<Activity> readPreferences();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Activity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreference", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreference")
    @ResponseWrapper(localName = "readPersonPreferenceResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.ReadPersonPreferenceResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonService/readPersonPreferenceRequest", output = "http://soap.assignment3.introsde/PersonService/readPersonPreferenceResponse")
    public Activity readPersonPreference(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "savePersonPreference", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.SavePersonPreference")
    @ResponseWrapper(localName = "savePersonPreferenceResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.SavePersonPreferenceResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonService/savePersonPreferenceRequest", output = "http://soap.assignment3.introsde/PersonService/savePersonPreferenceResponse")
    public void savePersonPreference(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Activity arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Activity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePersonPreference", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePersonPreference")
    @ResponseWrapper(localName = "updatePersonPreferenceResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.UpdatePersonPreferenceResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonService/updatePersonPreferenceRequest", output = "http://soap.assignment3.introsde/PersonService/updatePersonPreferenceResponse")
    public Activity updatePersonPreference(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Activity arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.assignment3.soap.Activity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "evaluatePersonPreference", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.EvaluatePersonPreference")
    @ResponseWrapper(localName = "evaluatePersonPreferenceResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.EvaluatePersonPreferenceResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonService/evaluatePersonPreferenceRequest", output = "http://soap.assignment3.introsde/PersonService/evaluatePersonPreferenceResponse")
    public Activity evaluatePersonPreference(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Activity arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Integer arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.assignment3.soap.Activity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBestPersonPreferences", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetBestPersonPreferences")
    @ResponseWrapper(localName = "getBestPersonPreferencesResponse", targetNamespace = "http://soap.assignment3.introsde/", className = "introsde.assignment3.soap.GetBestPersonPreferencesResponse")
    @Action(input = "http://soap.assignment3.introsde/PersonService/getBestPersonPreferencesRequest", output = "http://soap.assignment3.introsde/PersonService/getBestPersonPreferencesResponse")
    public List<Activity> getBestPersonPreferences(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
